//package gov.iti.jets.team5.models.freshStart;
//// Generated 23 Mar 2021, 23:39:24 by Hibernate Tools 6.0.0.Alpha2
//
//
//import gov.iti.jets.team5.models.dbEntities.CartItemsId;
//import gov.iti.jets.team5.models.freshStart.PotentialOrders;
//import gov.iti.jets.team5.models.freshStart.Product;
//
//import javax.persistence.*;
////LAST ONE NOT DONE
///**
// * CartItems generated by hbm2java
// */
//@Entity
//@Table(name = "cartItems"
//        , catalog = "ECommerceApp"
//)
//public class CartItems implements java.io.Serializable {
//
//
//    private CartItemsId id;
//    private PotentialOrders potentialOrders;
//    private Product product;
//    private int quantity;
//
//    public CartItems() {
//    }
//
//    public CartItems(CartItemsId id, PotentialOrders potentialOrders, Product product, int quantity) {
//        this.id = id;
//        this.potentialOrders = potentialOrders;
//        this.product = product;
//        this.quantity = quantity;
//    }
//
//    @EmbeddedId
//
//
//    @AttributeOverrides({
//            @AttributeOverride(name = "orderId", column = @Column(name = "orderId", nullable = false)),
//            @AttributeOverride(name = "productId", column = @Column(name = "productId", nullable = false))})
//    public CartItemsId getId() {
//        return this.id;
//    }
//
//    public void setId(CartItemsId id) {
//        this.id = id;
//    }
//
//    @ManyToOne(fetch = FetchType.LAZY)
//    @JoinColumn(name = "orderId", nullable = false, insertable = false, updatable = false)
//    public PotentialOrders getPotentialOrders() {
//        return this.potentialOrders;
//    }
//
//    public void setPotentialOrders(PotentialOrders potentialOrders) {
//        this.potentialOrders = potentialOrders;
//    }
//
//    @ManyToOne(fetch = FetchType.LAZY)
//    @JoinColumn(name = "productId", nullable = false, insertable = false, updatable = false)
//    public Product getProduct() {
//        return this.product;
//    }
//
//    public void setProduct(Product product) {
//        this.product = product;
//    }
//
//
//    @Column(name = "quantity", nullable = false)
//    public int getQuantity() {
//        return this.quantity;
//    }
//
//    public void setQuantity(int quantity) {
//        this.quantity = quantity;
//    }
//
//
//}
//
//
