//package gov.iti.jets.team5.models.freshStart;
//// Generated 23 Mar 2021, 23:39:24 by Hibernate Tools 6.0.0.Alpha2
//
//
//import gov.iti.jets.team5.models.freshStart.PotentialOrders;
//import gov.iti.jets.team5.models.freshStart.UserData;
//
//import javax.persistence.*;
//import java.util.Date;
//
///**
// * Orders generated by hbm2java
// */
//@Entity
//@Table(name = "orders"
//        , catalog = "ECommerceApp"
//)
//public class Order implements java.io.Serializable {
//
//    @Id
//    @GeneratedValue(strategy = GenerationType.IDENTITY)
//    @Column(name = "id", unique = true, nullable = false)
//    private int id;
//
//    //todo dunno yet
//    private PotentialOrders potentialOrders;
//
//    //todo dunno yet also to be named user as its mapped to that name in UserData entity!
//    private UserData userData;
//
//    @Temporal(TemporalType.DATE)
//    @Column(name = "orderDate", nullable = false)
//    private Date orderDate;
//
//    @Column(name = "total", nullable = false, precision = 10, scale = 2)
//    private long total;
//
//    public Order() {}
//
//    public Order(int id, PotentialOrders potentialOrders, UserData userData, Date orderDate, long total) {
//        this.id = id;
//        this.potentialOrders = potentialOrders;
//        this.userData = userData;
//        this.orderDate = orderDate;
//        this.total = total;
//    }
//
//    public int getId() {
//        return this.id;
//    }
//
//    public void setId(int id) {
//        this.id = id;
//    }
//
//    @ManyToOne(fetch = FetchType.LAZY)
//    @JoinColumn(name = "orderId", nullable = false)
//    public PotentialOrders getPotentialOrders() {
//        return this.potentialOrders;
//    }
//
//    public void setPotentialOrders(PotentialOrders potentialOrders) {
//        this.potentialOrders = potentialOrders;
//    }
//
//    @ManyToOne(fetch = FetchType.LAZY)
//    @JoinColumn(name = "userId", nullable = false)
//    public UserData getUserData() {
//        return this.userData;
//    }
//
//    public void setUserData(UserData userData) {
//        this.userData = userData;
//    }
//
//    public Date getOrderDate() {
//        return this.orderDate;
//    }
//
//    public void setOrderDate(Date orderDate) {
//        this.orderDate = orderDate;
//    }
//
//    public long getTotal() {
//        return this.total;
//    }
//
//    public void setTotal(long total) {
//        this.total = total;
//    }
//
//
//}
//
//
