//package gov.iti.jets.team5.models.freshStart;
//// Generated 23 Mar 2021, 23:39:24 by Hibernate Tools 6.0.0.Alpha2
//
//
//import gov.iti.jets.team5.models.dbEntities.CartItems;
//import gov.iti.jets.team5.models.freshStart.Order;
//import gov.iti.jets.team5.models.freshStart.UserData;
//
//import javax.persistence.*;
//import java.util.HashSet;
//import java.util.Set;
//
///**
// * PotentialOrders generated by hbm2java
// */
//@Entity
//@Table(name = "potential_orders"
//        , catalog = "ECommerceApp"
//)
//public class PotentialOrders implements java.io.Serializable {
//
//    //this orderId is enough to be the primary key right?
//    @Id
//    @GeneratedValue(strategy = GenerationType.IDENTITY)
//    @Column(name = "id", unique = true, nullable = false)
//    private int id;
//
//    @ManyToOne(fetch = FetchType.LAZY)
//    @JoinColumn(name = "userId", nullable = false, insertable = false, updatable = false)
//    private UserData user;
//
//    @Column(name = "active", columnDefinition = "bool default 'true'")
//    private boolean active;
//
//
//    //why the sets?
//    private Set<CartItems> cartItems = new HashSet<CartItems>(0);
//    private Set<Order> orders = new HashSet<Order>(0);
//
//    public PotentialOrders() {}
//
//    public PotentialOrders(int id, UserData user) {
//        this.id = id;
//        this.user = user;
//    }
//
//    public PotentialOrders(int id, UserData userData, Boolean active, Set<CartItems> cartItems, Set<Order> orders) {
//        this.id = id;
//        this.user = userData;
//        this.active = active;
//        this.cartItems = cartItems;
//        this.orders = orders;
//    }
//
//    public int getId() {
//        return this.id;
//    }
//
//    public void setId(int id) {
//        this.id = id;
//    }
//
//    public UserData getUserData() {
//        return this.user;
//    }
//
//    public void setUserData(UserData user) {
//        this.user = user;
//    }
//
//    public Boolean getActive() {
//        return this.active;
//    }
//
//    public void setActive(Boolean active) {
//        this.active = active;
//    }
//
//    @OneToMany(fetch = FetchType.LAZY, mappedBy = "potentialOrders")
//    public Set<CartItems> getCartItems() {
//        return this.cartItems;
//    }
//
//    public void setCartItems(Set<CartItems> cartItemses) {
//        this.cartItems = cartItemses;
//    }
//
//    @OneToMany(fetch = FetchType.LAZY, mappedBy = "potentialOrders")
//    public Set<Order> getOrders() {
//        return this.orders;
//    }
//
//    public void setOrders(Set<Order> orders) {
//        this.orders = orders;
//    }
//
//
//}
//
//
