//package gov.iti.jets.team5.models.freshStart;
//// Generated 23 Mar 2021, 23:39:24 by Hibernate Tools 6.0.0.Alpha2
//
//
//import gov.iti.jets.team5.models.dbEntities.CartItems;
//import gov.iti.jets.team5.models.dbEntities.Category;
//
//import javax.persistence.*;
//import java.util.HashSet;
//import java.util.Set;
//
///**
// * Product generated by hbm2java
// */
//@Entity
//@Table(name = "product"
//        , catalog = "ECommerceApp"
//)
//public class Product implements java.io.Serializable {
//
//    @Id
//    @GeneratedValue(strategy = GenerationType.IDENTITY)
//    @Column(name = "id", unique = true, nullable = false)
//    private int id;
//
//    @Column(name = "productName", nullable = false, length = 50)
//    private String productName;
//
//    @Column(name = "productDescription", nullable = false, length = 200)
//    private String productDescription;
//
//    @Column(name = "photo", nullable = false, length = 200)
//    private String photo;
//
//    @Column(name = "quantity", nullable = false)
//    private int quantity;
//
//    @Column(name = "price", nullable = false, precision = 10, scale = 2)
//    private long price;
//
//    @Column(name = "sellerName", nullable = false, length = 50)
//    private String sellerName;
//
//    @Column(name = "sold")
//    private int sold;
//
//    @ManyToMany(fetch = FetchType.LAZY)
//    @JoinTable(name = "product_categories", catalog = "ECommerceApp",
//            joinColumns = { @JoinColumn(name = "productId", nullable = false, updatable = false)},
//            inverseJoinColumns = { @JoinColumn(name = "categoryId", nullable = false, updatable = false)})
//    private Set<Category> categories = new HashSet<Category>(0);
//
//
//    private Set<CartItems> cartItems = new HashSet<CartItems>(0);
//
//    public Product() {
//    }
//
//
//    public Product(int id, String productName, String productDescription, String photo, int quantity, long price, String sellerName) {
//        this.id = id;
//        this.productName = productName;
//        this.productDescription = productDescription;
//        this.photo = photo;
//        this.quantity = quantity;
//        this.price = price;
//        this.sellerName = sellerName;
//    }
//
//    public Product(int id, String productName, String productDescription, String photo, int quantity, long price, String sellerName, int sold, Set<Category> categories, Set<CartItems> cartItems) {
//        this.id = id;
//        this.productName = productName;
//        this.productDescription = productDescription;
//        this.photo = photo;
//        this.quantity = quantity;
//        this.price = price;
//        this.sellerName = sellerName;
//        this.sold = sold;
//        this.categories = categories;
//        this.cartItems = cartItems;
//    }
//
//    public int getId() {
//        return this.id;
//    }
//
//    public void setId(int id) {
//        this.id = id;
//    }
//
//    public String getProductName() {
//        return this.productName;
//    }
//
//    public void setProductName(String productName) {
//        this.productName = productName;
//    }
//
//    public String getProductDescription() {
//        return this.productDescription;
//    }
//
//    public void setProductDescription(String productDescription) {
//        this.productDescription = productDescription;
//    }
//
//    public String getPhoto() {
//        return this.photo;
//    }
//
//    public void setPhoto(String photo) {
//        this.photo = photo;
//    }
//
//    public int getQuantity() {
//        return this.quantity;
//    }
//
//    public void setQuantity(int quantity) {
//        this.quantity = quantity;
//    }
//
//    public long getPrice() {
//        return this.price;
//    }
//
//    public void setPrice(long price) {
//        this.price = price;
//    }
//
//    public String getSellerName() {
//        return this.sellerName;
//    }
//
//    public void setSellerName(String sellerName) {
//        this.sellerName = sellerName;
//    }
//
//    public int getSold() {
//        return this.sold;
//    }
//
//    public void setSold(int sold) {
//        this.sold = sold;
//    }
//
//    public Set<Category> getCategories() {
//        return this.categories;
//    }
//
//    public void setCategories(Set<Category> categories) {
//        this.categories = categories;
//    }
//
//    @OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
//    public Set<CartItems> getCartItems() {
//        return this.cartItems;
//    }
//
//    public void setCartItems(Set<CartItems> cartItems) {
//        this.cartItems = cartItems;
//    }
//
//
//}
//
//
