package dbEntities;
// Generated 23 Mar 2021, 23:39:24 by Hibernate Tools 6.0.0.Alpha2


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Bank generated by hbm2java
 */
@Entity
@Table(name="bank"
    ,catalog="ECommerceApp"
    , uniqueConstraints = @UniqueConstraint(columnNames="creditNumber") 
)
public class Bank  implements java.io.Serializable {


     private int id;
     private String creditNumber;
     private String cvv;
     private Long balance;

    public Bank() {
    }

	
    public Bank(int id, String creditNumber, String cvv) {
        this.id = id;
        this.creditNumber = creditNumber;
        this.cvv = cvv;
    }
    public Bank(int id, String creditNumber, String cvv, Long balance) {
       this.id = id;
       this.creditNumber = creditNumber;
       this.cvv = cvv;
       this.balance = balance;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="creditNumber", unique=true, nullable=false, length=16)
    public String getCreditNumber() {
        return this.creditNumber;
    }
    
    public void setCreditNumber(String creditNumber) {
        this.creditNumber = creditNumber;
    }

    
    @Column(name="cvv", nullable=false, length=3)
    public String getCvv() {
        return this.cvv;
    }
    
    public void setCvv(String cvv) {
        this.cvv = cvv;
    }

    
    @Column(name="balance", precision=10, scale=0)
    public Long getBalance() {
        return this.balance;
    }
    
    public void setBalance(Long balance) {
        this.balance = balance;
    }




}


