package gov.iti.jets.team5.models.dbEntities;
// Generated 24 Mar 2021, 21:32:50 by Hibernate Tools 6.0.0.Alpha2


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CartItemsId generated by hbm2java
 */
@Embeddable
public class CartItemsId implements java.io.Serializable {


    private int orderId;
    private int productId;

    public CartItemsId() {
    }

    public CartItemsId(int orderId, int productId) {
        this.orderId = orderId;
        this.productId = productId;
    }


    @Column(name = "orderId", nullable = false)
    public int getOrderId() {
        return this.orderId;
    }

    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }


    @Column(name = "productId", nullable = false)
    public int getProductId() {
        return this.productId;
    }

    public void setProductId(int productId) {
        this.productId = productId;
    }


    public boolean equals(Object other) {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof CartItemsId)) return false;
        CartItemsId castOther = (CartItemsId) other;

        return (this.getOrderId() == castOther.getOrderId())
                && (this.getProductId() == castOther.getProductId());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getOrderId();
        result = 37 * result + this.getProductId();
        return result;
    }


}


