package gov.iti.jets.team5.models.dbEntities;
// Generated 24 Mar 2021, 21:32:50 by Hibernate Tools 6.0.0.Alpha2


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CartItems generated by hbm2java
 */
@Entity
@Table(name = "cartItems"
        , catalog = "ECommerceApp"
)
public class CartItems implements java.io.Serializable {


    private CartItemsId id;
    private PotentialOrders potentialOrders;
    private Product product;
    private int quantity;

    public CartItems() {
    }

    public CartItems(CartItemsId id, PotentialOrders potentialOrders, Product product, int quantity) {
        this.id = id;
        this.potentialOrders = potentialOrders;
        this.product = product;
        this.quantity = quantity;
    }

    @EmbeddedId


    @AttributeOverrides({
            @AttributeOverride(name = "orderId", column = @Column(name = "orderId", nullable = false)),
            @AttributeOverride(name = "productId", column = @Column(name = "productId", nullable = false))})
    public CartItemsId getId() {
        return this.id;
    }

    public void setId(CartItemsId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "orderId", nullable = false, insertable = false, updatable = false)
    public PotentialOrders getPotentialOrders() {
        return this.potentialOrders;
    }

    public void setPotentialOrders(PotentialOrders potentialOrders) {
        this.potentialOrders = potentialOrders;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "productId", nullable = false, insertable = false, updatable = false)
    public Product getProduct() {
        return this.product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }


    @Column(name = "quantity", nullable = false)
    public int getQuantity() {
        return this.quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }


}


