package dbEntities;
// Generated 23 Mar 2021, 23:39:24 by Hibernate Tools 6.0.0.Alpha2


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name="orders"
    ,catalog="ECommerceApp"
)
public class Orders  implements java.io.Serializable {


     private int id;
     private PotentialOrders potentialOrders;
     private UserData userData;
     private Date orderDate;
     private long total;

    public Orders() {
    }

    public Orders(int id, PotentialOrders potentialOrders, UserData userData, Date orderDate, long total) {
       this.id = id;
       this.potentialOrders = potentialOrders;
       this.userData = userData;
       this.orderDate = orderDate;
       this.total = total;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="orderId", nullable=false)
    public PotentialOrders getPotentialOrders() {
        return this.potentialOrders;
    }
    
    public void setPotentialOrders(PotentialOrders potentialOrders) {
        this.potentialOrders = potentialOrders;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="userId", nullable=false)
    public UserData getUserData() {
        return this.userData;
    }
    
    public void setUserData(UserData userData) {
        this.userData = userData;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="orderDate", nullable=false, length=10)
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    
    @Column(name="total", nullable=false, precision=10, scale=0)
    public long getTotal() {
        return this.total;
    }
    
    public void setTotal(long total) {
        this.total = total;
    }




}


