package gov.iti.jets.team5.models.dbEntities;
// Generated 24 Mar 2021, 21:32:50 by Hibernate Tools 6.0.0.Alpha2


import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * PotentialOrders generated by hbm2java
 */
@Entity
@Table(name = "potential_orders"
        , catalog = "ECommerceApp"
)
public class PotentialOrders implements java.io.Serializable {


    private int orderId;
    private UserData userData;
    private Boolean active;
    private Set<CartItems> cartItemses = new HashSet<CartItems>(0);
    private Set<Orders> orderses = new HashSet<Orders>(0);

    public PotentialOrders() {
    }


    public PotentialOrders(int orderId, UserData userData) {
        this.orderId = orderId;
        this.userData = userData;
    }

    public PotentialOrders(int orderId, UserData userData, Boolean active, Set<CartItems> cartItemses, Set<Orders> orderses) {
        this.orderId = orderId;
        this.userData = userData;
        this.active = active;
        this.cartItemses = cartItemses;
        this.orderses = orderses;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "orderId", unique = true, nullable = false)
    public int getOrderId() {
        return this.orderId;
    }

    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "userId", nullable = false)
    public UserData getUserData() {
        return this.userData;
    }

    public void setUserData(UserData userData) {
        this.userData = userData;
    }


    @Column(name = "active")
    public Boolean getActive() {
        return this.active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "potentialOrders")
    public Set<CartItems> getCartItemses() {
        return this.cartItemses;
    }

    public void setCartItemses(Set<CartItems> cartItemses) {
        this.cartItemses = cartItemses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "potentialOrders")
    public Set<Orders> getOrderses() {
        return this.orderses;
    }

    public void setOrderses(Set<Orders> orderses) {
        this.orderses = orderses;
    }


}


