package dbEntities;
// Generated 23 Mar 2021, 23:39:24 by Hibernate Tools 6.0.0.Alpha2


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PotentialOrdersId generated by hbm2java
 */
@Embeddable
public class PotentialOrdersId  implements java.io.Serializable {


     private int orderId;
     private int userId;

    public PotentialOrdersId() {
    }

    public PotentialOrdersId(int orderId, int userId) {
       this.orderId = orderId;
       this.userId = userId;
    }
   


    @Column(name="orderId", nullable=false)
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }


    @Column(name="userId", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PotentialOrdersId) ) return false;
		 PotentialOrdersId castOther = ( PotentialOrdersId ) other; 
         
		 return (this.getOrderId()==castOther.getOrderId())
 && (this.getUserId()==castOther.getUserId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getOrderId();
         result = 37 * result + this.getUserId();
         return result;
   }   


}


